package IT16117242;

import IT16117242.DBConnection.DBConnection;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.LocalDate;
import javax.swing.JOptionPane;


public class Payroll extends javax.swing.JInternalFrame {

    Connection con = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    
    
    /**
     * Creates new form Payroll
     */
    public Payroll() {
        initComponents();
         con= DBConnection.connect();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        eid = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        edesig = new javax.swing.JTextField();
        ename = new javax.swing.JTextField();
        etype = new javax.swing.JTextField();
        edep = new javax.swing.JTextField();
        esal = new javax.swing.JTextField();
        Search = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        calbtn = new javax.swing.JButton();
        savebtn = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        totalsal = new javax.swing.JTextField();
        OvrTimeMnthly = new javax.swing.JTextField();
        deduclvs = new javax.swing.JTextField();
        allow = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        monthCombo = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        OKbtn = new javax.swing.JButton();
        year = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        ExdLvs = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        absnt = new javax.swing.JTextField();
        resetbtn = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        deducabsnt = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel16 = new javax.swing.JLabel();
        ovrpay = new javax.swing.JTextField();
        allowancecalBtn = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        nopaylv = new javax.swing.JTextField();
        nopayabs = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        okAbs = new javax.swing.JButton();
        okLV = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setClosable(true);
        setTitle("Payroll");
        setPreferredSize(new java.awt.Dimension(950, 640));

        jPanel1.setBackground(new java.awt.Color(50, 50, 100));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(50, 50, 86), 3));
        jPanel1.setPreferredSize(new java.awt.Dimension(950, 640));

        jPanel2.setBackground(new java.awt.Color(131, 131, 131));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(540, 400));

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Employee ID");

        eid.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        eid.setPreferredSize(new java.awt.Dimension(180, 30));

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Designation");

        jLabel3.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Name");

        jLabel4.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Emp Type");

        jLabel5.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Department");

        jLabel6.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Basic Salary");

        edesig.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        edesig.setPreferredSize(new java.awt.Dimension(180, 30));
        edesig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edesigActionPerformed(evt);
            }
        });

        ename.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        ename.setPreferredSize(new java.awt.Dimension(180, 30));

        etype.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        etype.setPreferredSize(new java.awt.Dimension(180, 30));

        edep.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        edep.setPreferredSize(new java.awt.Dimension(180, 30));
        edep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edepActionPerformed(evt);
            }
        });

        esal.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        esal.setPreferredSize(new java.awt.Dimension(180, 30));

        Search.setBackground(new java.awt.Color(52, 52, 86));
        Search.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        Search.setForeground(new java.awt.Color(255, 255, 255));
        Search.setText("Search");
        Search.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.cyan, java.awt.Color.cyan, java.awt.Color.cyan, java.awt.Color.cyan));
        Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE))
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(edep, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                            .addComponent(etype, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                            .addComponent(ename, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                            .addComponent(edesig, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                            .addComponent(eid, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(esal, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addGap(42, 42, 42)
                .addComponent(Search, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(eid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Search))
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(edesig, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ename, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etype, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(edep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(esal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        jLabel10.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Overtime hrs");

        jLabel11.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Deduction lvs");

        jLabel12.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Allowance 0vrtm");

        calbtn.setBackground(new java.awt.Color(52, 52, 86));
        calbtn.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        calbtn.setForeground(new java.awt.Color(255, 255, 255));
        calbtn.setText("Calculate");
        calbtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.cyan, java.awt.Color.cyan, java.awt.Color.cyan, java.awt.Color.cyan));
        calbtn.setPreferredSize(new java.awt.Dimension(150, 30));
        calbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calbtnActionPerformed(evt);
            }
        });

        savebtn.setBackground(new java.awt.Color(52, 52, 86));
        savebtn.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        savebtn.setForeground(new java.awt.Color(255, 255, 255));
        savebtn.setText("Save");
        savebtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.cyan, java.awt.Color.cyan, java.awt.Color.cyan, java.awt.Color.cyan));
        savebtn.setPreferredSize(new java.awt.Dimension(150, 30));
        savebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savebtnActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Verdana", 1, 16)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Total salary");

        totalsal.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N

        OvrTimeMnthly.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        OvrTimeMnthly.setPreferredSize(new java.awt.Dimension(150, 30));

        deduclvs.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        deduclvs.setPreferredSize(new java.awt.Dimension(150, 30));
        deduclvs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deduclvsActionPerformed(evt);
            }
        });

        allow.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        allow.setPreferredSize(new java.awt.Dimension(150, 30));

        jPanel3.setBackground(new java.awt.Color(131, 131, 131));
        jPanel3.setPreferredSize(new java.awt.Dimension(540, 170));

        jLabel9.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Month");

        monthCombo.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        monthCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select one", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));
        monthCombo.setPreferredSize(new java.awt.Dimension(180, 30));
        monthCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                monthComboActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Year");

        OKbtn.setBackground(new java.awt.Color(52, 52, 86));
        OKbtn.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        OKbtn.setForeground(new java.awt.Color(255, 255, 255));
        OKbtn.setText("OK");
        OKbtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.cyan, java.awt.Color.cyan, java.awt.Color.cyan, java.awt.Color.cyan));
        OKbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OKbtnActionPerformed(evt);
            }
        });

        year.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Exceeded Leaves");

        ExdLvs.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        ExdLvs.setPreferredSize(new java.awt.Dimension(180, 30));

        jLabel7.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Abscents");

        absnt.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        absnt.setPreferredSize(new java.awt.Dimension(180, 30));

        resetbtn.setBackground(new java.awt.Color(52, 52, 86));
        resetbtn.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        resetbtn.setForeground(new java.awt.Color(255, 255, 255));
        resetbtn.setText("RESET");
        resetbtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.cyan, java.awt.Color.cyan, java.awt.Color.cyan, java.awt.Color.cyan));
        resetbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(74, 74, 74)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(year)
                            .addComponent(monthCombo, 0, 168, Short.MAX_VALUE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(absnt, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                            .addComponent(ExdLvs, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(OKbtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(resetbtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(monthCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(OKbtn))
                .addGap(15, 15, 15)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(year, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(ExdLvs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(absnt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(resetbtn))
                .addContainerGap())
        );

        jLabel14.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Deduction absnt");

        deducabsnt.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        deducabsnt.setPreferredSize(new java.awt.Dimension(150, 30));

        jLabel16.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Ovritme Pay");

        ovrpay.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        ovrpay.setPreferredSize(new java.awt.Dimension(150, 30));

        allowancecalBtn.setBackground(new java.awt.Color(52, 52, 86));
        allowancecalBtn.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        allowancecalBtn.setForeground(new java.awt.Color(255, 255, 255));
        allowancecalBtn.setText("allowance");
        allowancecalBtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.cyan, java.awt.Color.cyan, java.awt.Color.cyan, java.awt.Color.cyan));
        allowancecalBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                allowancecalBtnActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Deduction lv");

        jLabel18.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        jLabel18.setForeground(java.awt.Color.white);
        jLabel18.setText("Deduction ab");

        nopaylv.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        nopaylv.setPreferredSize(new java.awt.Dimension(180, 30));

        nopayabs.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        nopayabs.setPreferredSize(new java.awt.Dimension(180, 30));

        okAbs.setBackground(new java.awt.Color(52, 52, 86));
        okAbs.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        okAbs.setForeground(new java.awt.Color(255, 255, 255));
        okAbs.setText("Ok");
        okAbs.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.cyan, java.awt.Color.cyan, java.awt.Color.cyan, java.awt.Color.cyan));
        okAbs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okAbsActionPerformed(evt);
            }
        });

        okLV.setBackground(new java.awt.Color(52, 52, 86));
        okLV.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        okLV.setForeground(new java.awt.Color(255, 255, 255));
        okLV.setText("Ok");
        okLV.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.cyan, java.awt.Color.cyan, java.awt.Color.cyan, java.awt.Color.cyan));
        okLV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okLVActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 488, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 488, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(ovrpay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(deducabsnt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(OvrTimeMnthly, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(deduclvs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(allow, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(nopaylv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(nopayabs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(allowancecalBtn)
                                    .addComponent(okLV, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(okAbs, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(60, 60, 60))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSeparator3, javax.swing.GroupLayout.DEFAULT_SIZE, 406, Short.MAX_VALUE)
                                    .addComponent(jSeparator2)
                                    .addComponent(jSeparator1)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel13)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(totalsal, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(calbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(savebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(53, 53, 53)))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(203, 203, 203))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(nopaylv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(okLV)
                                .addGap(10, 10, 10)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel11)
                                    .addComponent(deduclvs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(nopayabs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel18)))
                            .addComponent(jLabel17))
                        .addGap(10, 10, 10)
                        .addComponent(okAbs)
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(deducabsnt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(36, 36, 36)
                                .addComponent(OvrTimeMnthly, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ovrpay, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addComponent(allowancecalBtn)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(allow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)))
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(calbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(savebtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(totalsal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGap(88, 88, 88))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void deduclvsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deduclvsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deduclvsActionPerformed

    private void SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchActionPerformed
        
         String Id = eid.getText();
         String yr = year.getText();
         String mnth = monthCombo.getSelectedItem().toString();
         
          double LeavTak = 0;
        
       try
       {
        String sql ="SELECT id,name,department,Salary,designation,EmpType FROM staff WHERE id='"+Id+"' AND Employd='Yes'";
        pst = con.prepareStatement(sql);
        rs = pst.executeQuery();
        
       
       
        eid.setText("");
        ename.setText("");
        edep.setText("");
        esal.setText("");
        edesig.setText("");
        etype.setText("");
    
 
        while(rs.next())
        {
        
            eid.setText(rs.getString("id"));
            ename.setText(rs.getString("name"));
            edep.setText(rs.getString("department"));
            esal.setText(rs.getString("Salary"));
            edesig.setText(rs.getString("designation"));
            etype.setText(rs.getString("EmpType"));
            
        }
        
        System.out.println("Data took sucessfully");
        
         
        
        
        }
       catch(SQLException e)
       {
            System.out.println(e);
       }
        
        
        
        
    }//GEN-LAST:event_SearchActionPerformed

    private void edepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edepActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edepActionPerformed

    private void OKbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OKbtnActionPerformed
        
         String Id = eid.getText();
         String yr = year.getText();
         String mnth = monthCombo.getSelectedItem().toString();
         
         ExdLvs.setText("");
         
          double LeavTak = 0;
          double ovrt=0;
          double allowance=0;
          double deductionexdlv=0;
          double deducAbsnt=0;
          double exd=0;
          int absnts=0;
          
          try{
          
          //Exceeded leaves calculation
      
        String sqlL="SELECT StaffID,FromDate,approval,SUM(LeavesNeeded) FROM leaves WHERE StaffID='"+Id+"' AND FromDate LIKE '%"+yr+"-"+mnth+"%' AND approval='Yes'";
        pst= con.prepareStatement(sqlL);
        rs = pst.executeQuery();
        
        
        while(rs.next())
        {
             LeavTak =rs.getDouble("SUM(LeavesNeeded)");
        
        }
        
        String sqlL1="SELECT EmpType FROM staff WHERE id='"+Id+"'";
        pst= con.prepareStatement(sqlL1);
        rs = pst.executeQuery();
        
         while(rs.next())
         {
          String Etype=rs.getString("EmpType");
            
            if(Etype.equalsIgnoreCase("Permanent") && LeavTak>4.0)
            {
                 exd = LeavTak-4.0;
                ExdLvs.setText(String.valueOf(exd));
            }
            else if(Etype.equalsIgnoreCase("Trainee") && LeavTak>2.0)
            {
                 exd = LeavTak-2.0;
                ExdLvs.setText(String.valueOf(exd));
            }
            
             
         }
         
        
          //calculate abscents
         //need 3 if elses
         //if mnth=31 days months categry
         //if mnth=30 days months categry
         //if mnth=02 and year%4==0
         //else absnts
       
        
        String sql9="SELECT StaffID,Date,COUNT(Name) FROM attendance WHERE StaffID='"+Id+"' AND Date LIKE '%"+yr+"-"+mnth+"%'";
        pst= con.prepareStatement(sql9);
        rs = pst.executeQuery();
        
        while(rs.next())
        {
            double Ename=rs.getInt("COUNT(Name)");
        
            if(Ename<31)
              {
                absnts=(int) (31.0-(LeavTak+Ename));
                absnt.setText(String.valueOf(absnts));
              }
            
        }
        
       
         //overtime per month
          OvrTimeMnthly.setText("");
        
        String sqlL7="SELECT StaffID,Date,SUM(Overtime) FROM attendance WHERE StaffID='"+Id+"' AND Date LIKE '%"+yr+"-"+mnth+"%'";
        pst= con.prepareStatement(sqlL7);
        rs = pst.executeQuery();
        
        while(rs.next())
        {
           OvrTimeMnthly.setText(rs.getString("SUM(Overtime)"));
           ovrt=rs.getDouble("SUM(Overtime)");
           
        }
       
         
        
         
        }
          catch(SQLException e)
       {
            System.out.println(e);
       }
          
         
          
          
         
         
        
    }//GEN-LAST:event_OKbtnActionPerformed

    private void monthComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_monthComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_monthComboActionPerformed

    private void edesigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edesigActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edesigActionPerformed

    private void allowancecalBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_allowancecalBtnActionPerformed

         double Pay = Double.valueOf(ovrpay.getText());
         String Id = eid.getText();
         String yr = year.getText();
         String mnth = monthCombo.getSelectedItem().toString();
         
        
     
          double ovrt=0;
          double allowance=0;
        
     try{
         //overtime AND ALLOWANCE per month
          OvrTimeMnthly.setText("");
        
        String sqlL7="SELECT StaffID,Date,SUM(Overtime) FROM attendance WHERE StaffID='"+Id+"' AND Date LIKE '%"+yr+"-"+mnth+"%'";
        pst= con.prepareStatement(sqlL7);
        rs = pst.executeQuery();
        
        while(rs.next())
        {
           OvrTimeMnthly.setText(rs.getString("SUM(Overtime)"));
           ovrt=rs.getDouble("SUM(Overtime)");
           
           if(ovrt<=5)
           {
               allowance= (ovrt * Pay);
               allow.setText(String.valueOf(allowance));
           }
           else if(ovrt>5)
           {
               allowance= (ovrt * Pay);
               allow.setText(String.valueOf(allowance));
           }
            
        }
     }
        catch(SQLException e)
       {
            System.out.println(e);
       }
          
     
        
        
    }//GEN-LAST:event_allowancecalBtnActionPerformed

    private void okLVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okLVActionPerformed
       
         double npaylv = Double.valueOf(nopaylv.getText());
         String Id = eid.getText();
         String yr = year.getText();
         String mnth = monthCombo.getSelectedItem().toString();
         
         ExdLvs.setText("");
         
          double LeavTak = 0;
          double deductionexdlv=0;
          double exd=0;
          
          try{
          
          //Exceeded leaves calculation
      
        String sqlL="SELECT StaffID,FromDate,approval,SUM(LeavesNeeded) FROM leaves WHERE StaffID='"+Id+"' AND FromDate LIKE '%"+yr+"-"+mnth+"%' AND approval='Yes'";
        pst= con.prepareStatement(sqlL);
        rs = pst.executeQuery();
        
        
        while(rs.next())
        {
             LeavTak =rs.getDouble("SUM(LeavesNeeded)");
        
        }
        
        String sqlL1="SELECT EmpType FROM staff WHERE id='"+Id+"'";
        pst= con.prepareStatement(sqlL1);
        rs = pst.executeQuery();
        
         while(rs.next())
         {
          String Etype=rs.getString("EmpType");
            
            if(Etype.equalsIgnoreCase("Permanent") && LeavTak>4.0)
            {
                 exd = LeavTak-4.0;
                ExdLvs.setText(String.valueOf(exd));
            }
            else if(Etype.equalsIgnoreCase("Trainee") && LeavTak>2.0)
            {
                 exd = LeavTak-2.0;
                ExdLvs.setText(String.valueOf(exd));
            }
            
              //calculate DEDUCTION  for exceeded leaves
        
        if(exd<=5)
            {
                deductionexdlv = (exd *npaylv);
                deduclvs.setText(String.valueOf(deductionexdlv));
            }
        else if(exd> 5)
            {
                deductionexdlv = (exd *npaylv);
                deduclvs.setText(String.valueOf(deductionexdlv));
            }
          
             
         }
        }
          catch(SQLException e)
       {
            System.out.println(e);
       }
          
        
        
        
        
    }//GEN-LAST:event_okLVActionPerformed

    private void okAbsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okAbsActionPerformed
       
         
         double nopayAbsnt = Double.valueOf(nopayabs.getText());
         String Id = eid.getText();
         String yr = year.getText();
         String mnth = monthCombo.getSelectedItem().toString();
         
        
          double deducAbsnt=0;
          int absnts=0;
          
          try{

         //calculate abscents
         //need 3 if elses
         //if mnth=31 days months categry
         //if mnth=30 days months categry
         //if mnth=02 and year%4==0
         //else absnts
       
        
        String sql9="SELECT StaffID,Date,COUNT(Name) FROM attendance WHERE StaffID='"+Id+"' AND Date LIKE '%"+yr+"-"+mnth+"%'";
        pst= con.prepareStatement(sql9);
        rs = pst.executeQuery();
        
        while(rs.next())
        {
            int Ename=rs.getInt("COUNT(Name)");
        
            if(Ename<31)
              {
                absnts=31-Ename;
                absnt.setText(String.valueOf(absnts));
              }
            
            //calculate DEDUCTION  for absnt days
        
        if(absnts<=5)
            {
                 deducAbsnt = (absnts*nopayAbsnt);
                deducabsnt.setText(String.valueOf( deducAbsnt));
            }
        else if(absnts> 5)
            {
                 deducAbsnt= (absnts*nopayAbsnt);
                deducabsnt.setText(String.valueOf( deducAbsnt));
            }
          
            
        }
       }
          
           catch(SQLException e)
       {
            System.out.println(e);
       }
          
        
    
        
        
    }//GEN-LAST:event_okAbsActionPerformed

    private void calbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calbtnActionPerformed
       
        double deduclv = Double.valueOf(deduclvs.getText());
        double deducAbsnt = Double.valueOf(deducabsnt.getText());
        double allownce = Double.valueOf(allow.getText());
        double basicsal = Double.valueOf(esal.getText());
        
        
        
        double TotalSal=0;
        
        TotalSal = basicsal+allownce-deduclv-deducAbsnt;
        totalsal.setText(String.valueOf(TotalSal));
        
    }//GEN-LAST:event_calbtnActionPerformed

    private void resetbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetbtnActionPerformed
       
        deduclvs.setText("");
        deducabsnt.setText("");
        allow.setText("");
        esal.setText("");
        totalsal.setText("");
        deducabsnt.setText("");
        absnt.setText("");
        nopayabs.setText("");
        eid.setText("");
        year.setText("");
        monthCombo.setSelectedItem(null);
        OvrTimeMnthly.setText("");
        ovrpay.setText("");
        nopaylv.setText("");
        edesig.setText("");
        ename.setText("");
        etype.setText("");
        eid.setText("");
        edep.setText("");
        ExdLvs.setText("");
      
         
        
        
        
    }//GEN-LAST:event_resetbtnActionPerformed

    private void savebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savebtnActionPerformed
        
        
        String mnth = monthCombo.getSelectedItem().toString();
        double amnt = Double.valueOf(totalsal.getText());
        String id = eid.getText();
        String yr = year.getText();
       
        try{
             
        
        String qry1 = "INSERT INTO expenses(amount,staffID,month,Year) values('"+amnt+"','"+id+"','"+mnth+"','"+yr+"')";
        
        pst = con.prepareStatement(qry1);
        pst.execute();
        System.out.println("Data added sucessfully");
        
        Confirmation C =new Confirmation("Details successfully added");
        C.setVisible(true);
        C.setLocationRelativeTo(this);
                }
       catch(SQLException e)
       {
           System.out.println("There is an exception"+e);
           
       }
            
       
        
        
    }//GEN-LAST:event_savebtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ExdLvs;
    private javax.swing.JButton OKbtn;
    private javax.swing.JTextField OvrTimeMnthly;
    private javax.swing.JButton Search;
    private javax.swing.JTextField absnt;
    private javax.swing.JTextField allow;
    private javax.swing.JButton allowancecalBtn;
    private javax.swing.JButton calbtn;
    private javax.swing.JTextField deducabsnt;
    private javax.swing.JTextField deduclvs;
    private javax.swing.JTextField edep;
    private javax.swing.JTextField edesig;
    private javax.swing.JTextField eid;
    private javax.swing.JTextField ename;
    private javax.swing.JTextField esal;
    private javax.swing.JTextField etype;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JComboBox<String> monthCombo;
    private javax.swing.JTextField nopayabs;
    private javax.swing.JTextField nopaylv;
    private javax.swing.JButton okAbs;
    private javax.swing.JButton okLV;
    private javax.swing.JTextField ovrpay;
    private javax.swing.JButton resetbtn;
    private javax.swing.JButton savebtn;
    private javax.swing.JTextField totalsal;
    private javax.swing.JTextField year;
    // End of variables declaration//GEN-END:variables

    
}
