/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package IT17026376;

import IT17029896.CheckOut;
import hotelsystem.Login;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author ACHINTHA-PC
 */
public class Cashier extends javax.swing.JFrame {
   
    private Connection connection = null;
    private Statement statement = null;
    private ResultSet resultSet = null;
    private final String url = "jdbc:mysql://localhost:3306/hotelsystem";
    private final String user = "root";
    private final String password = "";
    private final String driver = "com.mysql.jdbc.Driver";
    private Connection con = null;
    private PreparedStatement pst = null;
    private ResultSet rs = null;
    private volatile double discount = 0;
    private int TableNumber;
    private double amount = 0;
    private final String dName = null;
    

    /**
     * Creates new form Cashier
     */
    public Cashier() {
        initComponents();
        
        jLabel14.setVisible(false);
        jLabel15.setVisible(false);
        cashbox.setVisible(false);
        balancebox.setVisible(false);
        
        
        checkTable T = new checkTable();
        T.start();
    }
     class checkTable extends Thread
    {
        
        @Override
        public void run()
        { 
            try
            {
                Class.forName(driver);
                connection = DriverManager.getConnection(url,user,password);
                statement=connection.createStatement();

                    String sql ="SELECT Message FROM messages Where Message LIKE '%Table Number%'";
                    resultSet = statement.executeQuery(sql);
                    while(resultSet.next())
                    {
                         messageBox.setText( messageBox.getText()+"\n"+resultSet.getString("Message"));
                        TableNumber = Integer.parseInt(resultSet.getString("Message").replaceAll("\\D+",""));
                        
                                
                    }
                    
                    String sql2 ="SELECT Message FROM messages Where Message LIKE '%Set Discount: Discount Rate%'";
                    resultSet = statement.executeQuery(sql2);
                    while(resultSet.next())
                    {
                        discount = Double.parseDouble(resultSet.getString("Message").replaceAll("\\D+",""));
                        discountBox.setText(discount+"%");
                    }

                    Thread.sleep(1000);     //1 second
                
            }
            catch (Exception e) {
            e.printStackTrace();
            }
 
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jButton6 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        tablebox = new javax.swing.JTextField();
        discountBox = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        amountbox = new javax.swing.JTextField();
        Creditcheckbox = new javax.swing.JCheckBox();
        cashcheckbox = new javax.swing.JCheckBox();
        jLabel14 = new javax.swing.JLabel();
        cashbox = new javax.swing.JTextField();
        balancebox = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        messageBox = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        area = new javax.swing.JTextArea();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(50, 50, 86));

        jButton6.setBackground(new java.awt.Color(100, 255, 218));
        jButton6.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jButton6.setText("Logout");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Table Number: ");

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Take Payments ");

        tablebox.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        tablebox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tableboxActionPerformed(evt);
            }
        });

        discountBox.setEditable(false);
        discountBox.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        discountBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                discountBoxActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Discount: ");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Amount: ");

        amountbox.setEditable(false);
        amountbox.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        amountbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amountboxActionPerformed(evt);
            }
        });

        Creditcheckbox.setBackground(new java.awt.Color(50, 50, 86));
        Creditcheckbox.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        Creditcheckbox.setForeground(new java.awt.Color(255, 255, 255));
        Creditcheckbox.setText("Credit Card");
        Creditcheckbox.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Creditcheckbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreditcheckboxActionPerformed(evt);
            }
        });

        cashcheckbox.setBackground(new java.awt.Color(50, 50, 86));
        cashcheckbox.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        cashcheckbox.setForeground(new java.awt.Color(255, 255, 255));
        cashcheckbox.setText("Cash");
        cashcheckbox.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cashcheckbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cashcheckboxActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Cash: ");

        cashbox.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        cashbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cashboxActionPerformed(evt);
            }
        });

        balancebox.setEditable(false);
        balancebox.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        balancebox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                balanceboxActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Balance: ");

        jButton7.setBackground(new java.awt.Color(0, 153, 153));
        jButton7.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jButton7.setText("Take Payment");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        messageBox.setBackground(new java.awt.Color(255, 255, 255));
        messageBox.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        messageBox.setForeground(new java.awt.Color(255, 255, 255));
        messageBox.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        messageBox.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Message From Restaurant");

        area.setEditable(false);
        area.setBackground(new java.awt.Color(204, 204, 255));
        area.setColumns(20);
        area.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        area.setRows(5);
        jScrollPane3.setViewportView(area);

        jButton9.setBackground(new java.awt.Color(0, 153, 153));
        jButton9.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButton9.setText("Generate receipt");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton10.setBackground(new java.awt.Color(0, 153, 153));
        jButton10.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButton10.setText("Reset");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jButton11.setBackground(new java.awt.Color(0, 153, 153));
        jButton11.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jButton11.setText("Receipt Print");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Cashier");

        jButton8.setBackground(new java.awt.Color(0, 153, 153));
        jButton8.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jButton8.setText("POS Report");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(322, 322, 322)
                .addComponent(jButton9)
                .addGap(18, 18, 18)
                .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel13)
                                        .addComponent(jLabel12)))
                                .addGap(54, 54, 54))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(99, 99, 99)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel15)
                                            .addComponent(jLabel14)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(29, 29, 29)
                                        .addComponent(cashcheckbox, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(45, 45, 45)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(amountbox, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(discountBox, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                                        .addComponent(tablebox))))
                            .addComponent(cashbox, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Creditcheckbox, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(balancebox, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(messageBox, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel17)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton6)
                        .addGap(53, 53, 53))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton9)
                            .addComponent(jButton10)
                            .addComponent(jButton11)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(jLabel1)
                                .addGap(52, 52, 52)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel10)
                                    .addComponent(tablebox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(43, 43, 43)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel12)
                                    .addComponent(discountBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(47, 47, 47)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel13)
                                            .addComponent(amountbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(76, 76, 76))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(Creditcheckbox, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(cashcheckbox, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(59, 59, 59)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel14)
                                    .addComponent(cashbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(57, 57, 57)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel15)
                                    .addComponent(balancebox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(44, 44, 44)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButton7)
                                    .addComponent(jButton8)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(55, 55, 55)
                                        .addComponent(jLabel17)
                                        .addGap(21, 21, 21))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(jLabel11)
                                        .addGap(29, 29, 29)))
                                .addComponent(messageBox, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 34, Short.MAX_VALUE)))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
     
       
       Login L = new Login();
       L.setVisible(true);
       L.setLocationRelativeTo(null);
       L.setExtendedState(JFrame.MAXIMIZED_BOTH);
       this.dispose();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void tableboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tableboxActionPerformed
        
          try
        {
            String sql ="SELECT price FROM tables Where tid ="+TableNumber;
                 
                    resultSet = statement.executeQuery(sql);
                    while(resultSet.next())
                    {
                        amount = resultSet.getDouble("price");
                        amount = amount - (amount * (discount/100));
                        amountbox.setText(String.valueOf(amount));
                        
                    }
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
        
    }//GEN-LAST:event_tableboxActionPerformed

    private void discountBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_discountBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_discountBoxActionPerformed

    private void amountboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amountboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_amountboxActionPerformed

    private void CreditcheckboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreditcheckboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CreditcheckboxActionPerformed

    private void cashcheckboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cashcheckboxActionPerformed
       
         Creditcheckbox.setSelected(false);
        
        if(cashcheckbox.isSelected()==true)
        {
            jLabel14.setVisible(true);
            jLabel15.setVisible(true);
            cashbox.setVisible(true);
            balancebox.setVisible(true);
        }
        else
        {
            jLabel14.setVisible(false);
            jLabel15.setVisible(false);
            cashbox.setVisible(false);
            balancebox.setVisible(false);
        }
    }//GEN-LAST:event_cashcheckboxActionPerformed

    private void cashboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cashboxActionPerformed
        // TODO add your handling code here:
           double balance = Double.parseDouble(cashbox.getText());
        
        if(balance < amount){
            JOptionPane.showMessageDialog(null, "Invalid value");
        }
        else{
        balance = balance - amount;
        balancebox.setText(String.valueOf(balance));
        }
    }//GEN-LAST:event_cashboxActionPerformed

    private void balanceboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_balanceboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_balanceboxActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
       
            try{
            String sql =  "INSERT INTO payment "
                    + "(amount, discount, type)"
                    +" values( ?, ?, 'Resturant')";
            
            con = DriverManager.getConnection("jdbc:mysql://localhost/hotelsystem","root","");
            String user = "root";
            String password = "";
            String driver = "com.mysql.jdbc.Driver";
            pst = con.prepareStatement(sql);
            pst.setDouble(1,amount);
            pst.setDouble(2,discount);
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Take payment successfullly");

        }     
               catch(SQLException | HeadlessException e){
            JOptionPane.showMessageDialog(null,e);
            
        }
           
        
         try{
            String sql =  "UPDATE tables SET price = 0 WHERE tid="+TableNumber ;
            
            con = DriverManager.getConnection("jdbc:mysql://localhost/hotelsystem","root","");
            String user = "root";
            String password = "";
            String driver = "com.mysql.jdbc.Driver";
            pst = con.prepareStatement(sql);
            pst.executeUpdate();

        }     
               catch(SQLException | HeadlessException e){
            JOptionPane.showMessageDialog(null,e);
            
        }
         
         jLabel1.setText(jLabel1.getText().replaceAll("Table Number: "+TableNumber,""));
         
         try{
            String sql =  "DELETE FROM messages WHERE Message LIKE '%"+TableNumber+"%'" ;
            
            con = DriverManager.getConnection("jdbc:mysql://localhost/hotelsystem","root","");
            String user = "root";
            String password = "";
            String driver = "com.mysql.jdbc.Driver";
            pst = con.prepareStatement(sql);
            pst.executeUpdate();

        }     
               catch(SQLException | HeadlessException e){
            JOptionPane.showMessageDialog(null,e);
            
            
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
       
         // int tbox = Integer.valueOf(tablebox.getText());
              
        try {
            
                Class.forName(driver);
                connection = DriverManager.getConnection(url,user,password);
                statement=connection.createStatement();

                    String sql ="SELECT Message FROM messages Where Message LIKE '%Table Number%'";
                    resultSet = statement.executeQuery(sql);
                    while(resultSet.next())
                        
                    {
                         area.setText("                      ROYAL KANDIAN               \n");
               area.setText(area.getText()+"                   833 PERADENIYA RD              \n");
               area.setText(area.getText()+"                             KANDY           \n\n");
        
             Date obj = new Date();
             String date = obj.toString();
             area.setText(area.getText()+date+"\n");

                   area.setText(area.getText()+"Table number: "+tablebox.getText()+"\n\n");
                  area.setText(area.getText()+"QUANTITY       DESCRIPTION       AMOUNT\n");
                        jLabel1.setText(jLabel1.getText()+"\n"+resultSet.getString("Message"));
                        TableNumber = Integer.parseInt(resultSet.getString("Message").replaceAll("\\D+",""));
                                
                    }
                    
            String sql1 ="SELECT orders.tableNO,orders.quantity,menu.price,meals.foodName FROM orders,menu,meals " +
"WHERE orders.menuID = menu.ID " +
"AND meals.menuId = menu.ID "
                    + "AND orders.tableNO="+TableNumber;
            resultSet = statement.executeQuery(sql1);
        
            while(resultSet.next()){
                
                int quantity= resultSet.getInt("quantity");
                 String foodName = resultSet.getString("foodName");
               // String dName = resultSet.getString("dName");
                 double price = resultSet.getDouble("price");
               
                
         
            area.setText(area.getText()+"   "+quantity+"   \t       "+foodName+"\t        "+price+" \n");
                
            
            }
        } catch (Exception ex) {
            ex.printStackTrace();
            
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        
          area.setText("");
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
       
           int x = JOptionPane.showConfirmDialog(null, "Do you want to print the receipt");
        if(x == 0){
            try{
                area.print();
            }
            catch(Exception e){

            }

        }
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
                                    report G = new report();
                                        G.setVisible(true);
                                        G.setLocationRelativeTo(null);
                                        G.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }//GEN-LAST:event_jButton8ActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cashier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cashier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cashier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cashier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cashier().setVisible(true);
            }
        });

}


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox Creditcheckbox;
    private javax.swing.JTextField amountbox;
    private javax.swing.JTextArea area;
    private javax.swing.JTextField balancebox;
    private javax.swing.JTextField cashbox;
    private javax.swing.JCheckBox cashcheckbox;
    private javax.swing.JTextField discountBox;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel messageBox;
    private javax.swing.JTextField tablebox;
    // End of variables declaration//GEN-END:variables
}
