/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package IT17040518;


import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author Harish
 */
public class CancelReservation extends javax.swing.JFrame {
    
    private Connection connection = null;
    private Statement statement = null;
    private ResultSet resultSet = null;
    private final String url = "jdbc:mysql://localhost:3306/hotelsystem";
    private final String user = "root";
    private final String password = "";
    private final String driver = "com.mysql.jdbc.Driver";
    private int ID =0;
   

    /**
     * Creates new form CancelReservation
     */
    public CancelReservation() {
        initComponents();
        
                 CRTable.addMouseListener(new java.awt.event.MouseAdapter() {
        @Override
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            
           ID = Integer.parseInt((String) CRTable.getValueAt(CRTable.getSelectedRow(),0));
            
    }
});
        
        Calendar c = Rdate.getMonthView().getCalendar();
        c.setTime(new Date());
        Rdate.getMonthView().setLowerBound(c.getTime());
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        CRTable = new javax.swing.JTable();
        jLabel15 = new javax.swing.JLabel();
        Rdate = new org.jdesktop.swingx.JXDatePicker();
        Deletereservation = new javax.swing.JButton();
        NoCombo = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(50, 50, 86));

        jButton1.setBackground(new java.awt.Color(100, 255, 218));
        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton1.setText("←");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel6.setBackground(new java.awt.Color(29, 29, 66));

        jLabel3.setBackground(new java.awt.Color(0, 204, 255));
        jLabel3.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 255, 255));
        jLabel3.setText("Cancel Reservation of Table");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel3)
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        CRTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Reservation ID", "Table No", "Date", "Time", "Phone number", "No Of Guest"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(CRTable);
        if (CRTable.getColumnModel().getColumnCount() > 0) {
            CRTable.getColumnModel().getColumn(0).setResizable(false);
            CRTable.getColumnModel().getColumn(0).setHeaderValue("Reservation ID");
            CRTable.getColumnModel().getColumn(1).setResizable(false);
            CRTable.getColumnModel().getColumn(2).setResizable(false);
            CRTable.getColumnModel().getColumn(3).setResizable(false);
            CRTable.getColumnModel().getColumn(4).setResizable(false);
            CRTable.getColumnModel().getColumn(5).setResizable(false);
        }

        jLabel15.setBackground(new java.awt.Color(255, 255, 255));
        jLabel15.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Date");

        Rdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RdateActionPerformed(evt);
            }
        });

        Deletereservation.setBackground(new java.awt.Color(100, 255, 218));
        Deletereservation.setFont(new java.awt.Font("Verdana", 1, 16)); // NOI18N
        Deletereservation.setForeground(new java.awt.Color(50, 50, 86));
        Deletereservation.setText("Delete Table Reservation");
        Deletereservation.setToolTipText("");
        Deletereservation.setBorderPainted(false);
        Deletereservation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeletereservationActionPerformed(evt);
            }
        });

        NoCombo.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        NoCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Breakfast", "Lunch", "Dinner" }));
        NoCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NoComboActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addGap(155, 155, 155)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(76, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(18, 18, 18)
                        .addComponent(Rdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(91, 91, 91)
                        .addComponent(NoCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(77, 77, 77)
                        .addComponent(Deletereservation))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 749, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Deletereservation, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NoCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Rdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addGap(31, 31, 31)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(112, 112, 112))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        resturant R = new resturant();
        R.setVisible(true);
       
        R.setLocationRelativeTo(this);
        R.setExtendedState(this.getExtendedState());
        this.dispose();

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void RdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RdateActionPerformed

       
    }//GEN-LAST:event_RdateActionPerformed

    private void DeletereservationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeletereservationActionPerformed
              
              if(ID ==0)
        {
            JOptionPane.showMessageDialog(null, "Select a Row");
            return;
        }
        int time;
        try{
             Class.forName(driver);
            connection = DriverManager.getConnection(url,user,password);
            statement=connection.createStatement();
            
            
             
       if(NoCombo.getSelectedItem().toString().equalsIgnoreCase("Breakfast"))
            {
                time = 6;
            }
       else if (NoCombo.getSelectedItem().toString().equalsIgnoreCase("Lunch"))
            {
                time = 13;
            }
       else
       {
           time = 18;
       }
           

            String message;
            String sql3 ="SELECT Sender,Message,Receiver "
            + "FROM messages "
            + "WHERE Message LIKE '%Delete Table Reservation%'";
            resultSet = statement.executeQuery(sql3);

            while(resultSet.next())
            {
                if(resultSet.getString("Sender").equalsIgnoreCase("Resturant") && resultSet.getString("Receiver").equals("pos"))
                {
                    message = resultSet.getString("Message");
                    message = message.replaceAll("\\D+","");

                    if(Integer.parseInt(message)==ID)
                    {
                        JOptionPane.showMessageDialog(null, "Already requested pos to delete.");
                        return;
                    }
                }
            }

            String sql5 = "INSERT INTO messages(Sender,Message,Receiver) VALUES('Resturant',"
            + "'Delete Table Reservation: Reservation ID = "+ID+"','pos')";

            PreparedStatement pst = connection.prepareStatement(sql5);
            pst.executeUpdate();

        }catch(Exception e)
        {
            e.printStackTrace();
        }

        JOptionPane.showMessageDialog(null, "POS will delete the Reservation.");
       /* Alerts A = new Alerts("Accounting will delete the Reservation.");
        A.setDefaultCloseOperation(0);
        A.setVisible(true);
        A.setLocationRelativeTo(this);*/

    }//GEN-LAST:event_DeletereservationActionPerformed

    private void NoComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NoComboActionPerformed
        int time = 0;
       if(NoCombo.getSelectedItem().toString().equalsIgnoreCase("Breakfast"))
            {
                time = 6;
            }
       else if (NoCombo.getSelectedItem().toString().equalsIgnoreCase("Lunch"))
            {
                time = 13;
            }
       else
       {
           time = 18;
       }
        
        
        String contents[][]=new String[20][10];
        java.sql.Date date = new java.sql.Date(Rdate.getDate().getTime());
        
        try
        {
            connection = DriverManager.getConnection(url,user,password);
            statement=connection.createStatement();

            int i = 0;

            String Type = NoCombo.getSelectedItem().toString();
               if(Type.equalsIgnoreCase("Breakfast"))
            {
                time = 6;
            }
       else if (Type.equalsIgnoreCase("Lunch"))
            {
                time = 13;
            }
       else
       {
           time = 18;
       }
            String sql ="SELECT * FROM reservation WHERE time = '"+time+"'AND date = '"+date+"'";

            resultSet = statement.executeQuery(sql);
            while(resultSet.next())
            {
                contents[i][0]=resultSet.getString("id");
                contents[i][1]=resultSet.getString("tableNo");
                contents[i][2]=resultSet.getString("date");
                if(resultSet.getInt("time")== 6)
                {
                     contents[i][3]="Breakfast";
                }
                else if(resultSet.getInt("time")== 13)
                {
                    contents[i][3]="Lunch";
                }
                else
                {
                    contents[i][3]="Dinner";
                }
                contents[i][4]=resultSet.getString("Phone");
                contents[i][5]=resultSet.getString("noOfGuests");
                i=i+1;
            }
        }
        catch (Exception e)
        {
            e.printStackTrace();
        }

        CRTable.setModel(new javax.swing.table.DefaultTableModel(
            contents,
    new String [] {
        "Reservation ID","Table No", "Date", "Time", "Phone number", "No Of Guest"
    }
));
        
        
        
    }//GEN-LAST:event_NoComboActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CancelReservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CancelReservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CancelReservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CancelReservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CancelReservation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable CRTable;
    private javax.swing.JButton Deletereservation;
    private javax.swing.JComboBox<String> NoCombo;
    private org.jdesktop.swingx.JXDatePicker Rdate;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
